### ISSUE TITLE
Can't use nuxt-edge because 'nuxt' is being imported

### ISSUE THREAD

**Issue by gbruins-notours** [nuxt-community/hapi-nuxt#13]
This might be a moot point in the near future when Nuxt2 is released, but for now users of hapi-nuxt can no use [nuxt-edge](https://www.npmjs.com/package/nuxt-edge) because 'nuxt' is being imported on this line:

https://github.com/nuxt-community/hapi-nuxt/blob/eabb59352655e11352ae8b4a128e2d4defca16f5/src/index.js#L2

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/hapi-nuxt/issues/c9">#c9</a>)</em></sub></div>

**Comment by AndrewBogdanovTSS** [comment]
@gbruins-notours you will need to install nuxt-edge using a `nuxt` alias:
`npm:nuxt-edge@latest` 
and than you will be able to use at as usual nuxt dependencie
your package.json should look like this:
```
  "dependencies": {
    ...
    "nuxt": "npm:nuxt-edge@latest",
    ...
  }
```

**Comment by pi0** [comment]
Thanks, @AndrewBogdanovTSS for the workaround. Anyway we may add an option to pass Nuxt module for supporting nuxt-start and nuxt-edge family

**Comment by pi0** [comment]
Sorry for this long delay. With 2.0.0 it is possible to use nuxt-edge by setting `edge` to `true`.
