### ISSUE TITLE
Can't use nuxt-edge because 'nuxt' is being imported 

### ISSUE THREAD

**Issue by gbruins-notours** [nuxt-community/hapi-nuxt#14]
### Version

[1.0.1](https://github.com/hapi-nuxt/releases/tag/1.0.1)

### Reproduction link

[https://github.com/nuxt-community/hapi-nuxt/blob/eabb59352655e11352ae8b4a128e2d4defca16f5/src/index.js#L2](https://github.com/nuxt-community/hapi-nuxt/blob/eabb59352655e11352ae8b4a128e2d4defca16f5/src/index.js#L2)

### Steps to reproduce

This might be a moot point in the near future when Nuxt2 is released, but for now users of hapi-nuxt can no use nuxt-edge because 'nuxt' is being imported on this line:
https://github.com/nuxt-community/hapi-nuxt/blob/eabb59352655e11352ae8b4a128e2d4defca16f5/src/index.js#L2

### What is expected ?

To be able to use nuxt-edge

### What is actually happening?

Cant use nuxt-edge because 'nuxt' is being imported

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/hapi-nuxt/issues/c10">#c10</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi. With `2.0.0` it is now possible to specify using nuxt-edge by setting `edge` option to `true`.
