### ISSUE TITLE
hapi nuxt axios proxy only support get method

### ISSUE THREAD

**Issue by then198611** [nuxt-community/hapi-nuxt#16]
when i use nuxtjs/axios add proxy for api in nuxt.conf, i find the get method is ok,but others like post、put、delete... all return 404 

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/hapi-nuxt/issues/c11">#c11</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi. Starting with 2.1.0, default route method is `*` so proxy module should work fine.
