### ISSUE TITLE
Add base url setting

### ISSUE THREAD

**Issue by chomman** [nuxt-community/hapi-nuxt#19]
### What problem does this feature solve?

It is distinguished from the URLs registered in other hapi modules.

### What does the proposed changes look like?

I would like to add the ability to set a default url to use nuxt on a Hapi route.
I think it is necessary to utilize the modularization function of Hapi.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/hapi-nuxt/issues/c13">#c13</a>)</em></sub></div>

**Comment by pi0** [comment]
Supported in 2.0.0 via `baseURL`
