### ISSUE TITLE
hapi: This package has been deprecated

### ISSUE THREAD

**Issue by seekerlee** [nuxt-community/hapi-nuxt#27]
according to https://www.npmjs.com/package/hapi:

> This package has been deprecated
> Author message:
>
> This module has moved and is now available at @hapi/hapi. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.

maybe we should update the hapi dependency in package.json to @hapi/hapi, otherwise there will be many warnings during npm install.

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/hapi-nuxt/issues/c15">#c15</a>)</em></sub></div>

**Comment by openam** [comment]
It looks like many of the hapi packages added a breaking change requiring @hapi/hapi as a peer dependency.

**Comment by pi0** [comment]
@openam Yes. I'll release a major version soon to upgrade using `@hapi/hapi`

**Comment by pi0** [comment]
Upgraded in `2.2.0`
