### ISSUE TITLE
Debugging hapi-nuxt

### ISSUE THREAD

**Issue by chrissyast** [nuxt-community/hapi-nuxt#51]
I am trying to debug some code which is in...
`.nuxt/index.js`
which I believe is compiled from...
`node_modules/hapi-nuxt/example/.nuxt/index.js` (among other sources)
but even if I place a debugger in the latter file, there is still no debugger when I'm running the server.
So I believe that the latter file is in itself being compiled from another file. Where do I need to put a debugger in order for this to be rendered when I run the server?

**Comment by atinux** [comment]
We plan to deprecate this template in favour os using hapi as a servermiddleware for Nuxt, see #60

**Comment by pi0** [comment]
@Atinux  Using hapi as s serverMiddleware is not possible :) @chrissyast Feel free making a new question issue in nuxt/nuxt.js regarding debugging with programmatic usage.

**Comment by chrissyast** [comment]
@pi0 
> @chrissyast Feel free making a new question issue in nuxt/nuxt.js regarding debugging with programmatic usage.

I made this issue so long ago I don't even remember why I needed it
