### ISSUE TITLE
Can we get a tutorial? I would be willing to help write it.

### ISSUE THREAD

**Issue by SamuelEarl** [nuxt-community/hapi-nuxt#6]
Hi. Thank you for creating this plugin. I have been trying to figure out how to connect hapi.js and Vue.js for awhile now and I came across this plugin recently. 

I am trying to get this plugin to work with a hapi.js project that I am working on, but I keep getting errors. I am sure that I have some errors with my configs, but I don't know where I am going wrong. A tutorial would be much appreciated. I would be willing to help write it with your direction.

Please let me know what I can do to help and I would be glad to contribute.

Thank you!

**Comment by pi0** [comment]
Hi samuel! Happy interested in this plugin :) Would you please explain more about the errors you are currently getting? Also, a fresh github repo would be a good idea for start.

**Comment by SamuelEarl** [comment]
This is the error that I am getting:
-----
Build completed in 1.203s

ERROR  Failed to compile with 1 errors

This dependency was not found:

* /<path-to-project-root>/.nuxt/client.js in multi webpack-hot-middleware/client?name=$client&reload=true ./.nuxt/client.js

To install it, you can run: npm install --save /<path-to-project-root>/.nuxt/client.js
Server running at http://sam-Gazelle:4000
-----
When I try to install this, NPM doesn't install anything because it is not an NPM package. Also, when I visit http://localhost:4000/ the page never actually loads.

I am going to try this in a new project and I will send a GitHub link.

Thank you!

**Comment by SamuelEarl** [comment]
Hi @pi0,

Here is the GitHub repo for my example app: https://github.com/SamuelEarl/hapi-nuxt-example-app

**Comment by pi0** [comment]
Thanks for the repo. Actually, the problem is with your nuxt project dependencies which eslint is not available so removing that `extend` part from `nuxt.config.js` should resolve that problem. Also, consider directly adding `nuxt` and `es6-promise` to project dependencies.

**Comment by SamuelEarl** [comment]
That worked! I added all of the eslint files that are used in the Nuxt.js starter template, so I was able to keep the `extend` part in my `nuxt.config.js` file. I also added `nuxt` and `es6-promise` to my project dependencies. Now when I run `yarn start` it works!

Thank you so much! I love this plugin!

I have updated my GitHub repo to show these changes.

**Comment by ankitrg** [comment]
@SamuelEarl Is hapi + nuxt working out for you?

**Comment by ankitrg** [comment]
@pi0 Is there a sample app created using this plugin? It would help a lot.

**Comment by SamuelEarl** [comment]
Hi @pi0. I stepped away from working on my hapi-nuxt app, but I am trying to work on it again. I cannot get hapi to serve up any nuxt files. Do you have a sample server.js (or index.js or app.js) file for hapi that I can look at to see where I am going wrong? Would you also include a sample file structure so I can see if my file structure is missing anything? I think the issue is that I don't know how to configure hapi to serve up my nuxt layout files, but I would like to see how you configure your projects. Thank you very much!

**Comment by mitchellst** [comment]
I got this working today in both dev and prod modes.

Problem in brief: everything works great in dev mode, if you're running the nuxt builder. You require in your `nuxt.config.js`, feed it as `options` to this plugin, and it works like a charm in development. Production was trickier. When you run `nuxt build`, it creates `.nuxt/dist` in your nuxt source directory. (`srcDir` in the nuxt configuration.) The central issue is that any server-side-rendered nuxt pages are expecting the contents of this `dist` directory at `mysite.com/_nuxt/`. We can make that happen using [inert](https://github.com/hapijs/inert), hapi's plugin for serving static files.

In code:
```javascript

const Path = require('path')
const Hapi = require('hapi')
const Inert = require('inert')
const HapiNuxt = require('hapi-nuxt')

// Application code

// assume nuxt config is in a directory called "client" next to this file.
const NuxtConfig = require('./client/nuxt.config.js')
const NuxtStaticRoutes = require('./nuxt-static-routes') // see further down.

// Inert will resolve all static files relative to a location we set here. See Inert's readme.
const opts = {
  routes: {
    files: {
      relativeTo: Path.join(Path.resolve(__dirname), 'client')
    }
  }
}

const server = new Hapi.Server(opts)
server.connection({ host: '0.0.0.0', port: 8080})

// Set this however you want
const PROD_MODE = process.env.NODE_ENV !== 'dev'

// I'm not sure but I think the order of this array might be important in some cases
// NuxtStaticRoutes should come before HapiNuxt
const plugins = [
  Inert,
  {
    register: NuxtStaticRoutes,
    options: { PROD_MODE }
  },
  {
    register: HapiNuxt,
    options: PROD_MODE ? Object.assign(NuxtConfig, {dev: false}) : NuxtConfig
  }
]

server.register(plugins, err => {
  if (err) { throw err }
  server.start(
    err => {
      if (err) { throw err }
      console.log(`Hapi Nuxt Server running at 8080 in ${PROD_MODE ? 'prod' : 'dev'} mode.`)
    }
  )
})

```

Then, over in `nuxt-static-routes.js`:
```javascript

module.exports = { register }

function register(server, options, next) {
  // first up, let's serve nuxt's static directory.
  server.route({
    method: 'GET',
    path: '/static/{param*}',
    handler: {
      directory: {
        // remember this is relative to our client directory, as configured in opts above.
        // see Inert docs for details.
        path: 'static'
      }
    }
  })

  if (options.PROD_MODE) {
    // This is what hapi-nuxt seems to be missing.
    // We need to serve out the stuff built by the nuxt build command.
    server.route({
      method: 'GET',
      path: '_nuxt/{param*}',
      handler: {
        directory: {
          path: '.nuxt/dist'
        }
      }
    })
  }

  next()
}

// required for validation.
register.attributes = {
  name: 'NuxtStaticRoutes',
  version: '1.0.0'
}

```
YMMV on the exact routes by exactly how you decide to set up the directory structure in your repo. Pay attention to nuxt's `srcDir` (don't mess with `rootDir`) and the `relativeTo` path when you initialize your server. If you get stuck, try running `nuxt build` and find out where it put your `.nuxt` directory.

I'd be interested in helping integrate these static file issues into the plugin itself to make it work more simply out of the box. I haven't dug into the plugin's code, so I'm not quite sure what it would take. I suspect there would be a way to parse into the nuxt config the plugin receives as `options` and pull the paths out of there.

**Comment by SamuelEarl** [comment]
Wow! That is a great response! Thank you very much. I love all the detail and instructions in your answer. It would have taken me a really long time to figure all that out. I will give this a shot and let you know if I have any other questions. Thank you, again!

**Comment by microcipcip** [comment]
I am curious, considering how long it takes for Nuxt to rebuild at each change, wouldn't make more sense to just use Hapi as REST API with the @nuxtjs/proxy?
```
  modules: [
    '@nuxtjs/proxy'
  ],
  proxy: {
    '/api': 'http://localhost:3001',
    ws: true
  },
```

**Comment by mitchellst** [comment]
That would absolutely work. In many situations, using the proxy could make sense, and indeed, its much easier/simpler than what I put up above.

There are some use cases where the nuxt proxy setup won't meet your needs, and you need the pattern I put up. Off the top of my head, a few of those cases would be:
[1] You're trying to embed a nuxt app as a piece of a larger site that also has non-nuxt pieces. (my use case)
[2] You're an enterprise that has a bunch of approved Hapi middleware and standards for authentication, security, csrf, access monitoring, etc. You have to pass all requests through your hapi app for compliance with those standards.
[3] You're deploying on a PaaS like heroku or google app engine. You can only run one node process per container, you need a way to run your API and nuxt together, and listen on just one port; you can't proxy through to a different port. (Also something I've run into.)

So, it depends on your design needs. But I'll note, if you don't have one of those needs (i.e., the proxy solution works for you), then... you don't need this Hapi plugin! Just use exactly the configuration @microcipcip posted above and run them as two separate apps.

**Comment by microcipcip** [comment]
Thank you for the details reply @mitchellst! 

What about the slow rebuild of Nuxt? Did u find any workaround or do you just wait the 5secs it takes to rebuild each time you change something in the Hapi application?

**Comment by pi0** [comment]
Hi. I've just added an Example of usage:
https://github.com/nuxt-community/hapi-nuxt/tree/master/example.

BTW I agree about all of the comments regarding using a separate Hapi instance and using Proxy for API. We are doing the same at Fandogh for a while. See [proxy module](https://github.com/nuxt-community/modules/tree/master/packages/proxy) and [axios module](https://github.com/nuxt-community/axios-module)

Also feel free opening PRs for more Tutorials and Information :)

**Comment by kshoultz** [comment]
Would this explain why my nuxt configuration for my css shows up local but not on my heroku deployment?
